name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake Game from a GitHub Contribution Graph
        uses: Platane/snk@v1.0.0
        with:
          github_user_name: patriciajunqueira
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push Snake Game to the output branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: output
          file: dist/github-contribution-grid-snake.svg
          token: ${{ secrets.PAT_TOKEN }}
